ALTER TABLE "exam_types"
ADD COLUMN "study_track" TEXT,
ADD COLUMN "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "exam_subjects"
ADD COLUMN "points_per_item" DOUBLE PRECISION,
ADD COLUMN "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
