ALTER TABLE "exam_types"
ADD COLUMN IF NOT EXISTS "study_track" TEXT,
ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "exam_subjects"
ADD COLUMN IF NOT EXISTS "points_per_item" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
